/**
 * Generate `src/shared/constants/kinds.ts` from `crates/buzz-core/src/kind.rs`.
 *
 * The Rust file is the single source of truth for every event-kind integer
 * (AGENTS.md: "All event kind integers are defined in buzz-core/src/kind.rs").
 * Hand-copying them into TypeScript is how desktop and mobile drifted; this
 * generator plus `--check` makes drift a CI failure instead of a bug report.
 *
 *   node scripts/gen-kinds.mjs           # write the file
 *   node scripts/gen-kinds.mjs --check   # fail if the file is stale
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const KIND_RS = path.resolve(projectRoot, "../crates/buzz-core/src/kind.rs");
const OUT = path.resolve(projectRoot, "src/shared/constants/kinds.ts");

/**
 * Kinds the web client actually uses. Generating all 126 would be noise the
 * file-size guard would eventually trip over, and an unused constant is a
 * liability rather than documentation — add here when a surface needs one.
 */
const WANTED = [
  "KIND_PROFILE",
  "KIND_PERSONA",
  "KIND_TEAM",
  "KIND_MANAGED_AGENT",
  "KIND_AGENT_RUNTIME_STATUS",
  "KIND_INTEL_GATEWAY_CATALOG",
  "KIND_AGENT_TURN_METRIC",
  "KIND_AGENT_OBSERVER_FRAME",
  "KIND_GIT_REPO_ANNOUNCEMENT",
  "KIND_GIT_REPO_STATE",
  "KIND_AUTH",
  "KIND_REACTION",
  "KIND_STREAM_MESSAGE",
  "KIND_STREAM_MESSAGE_V2",
  "KIND_NIP29_GROUP_METADATA",
];

/** Turn `KIND_MANAGED_AGENT` into `MANAGED_AGENT`. */
function tsName(rustName) {
  return rustName.replace(/^KIND_/, "");
}

async function parseKinds() {
  const source = await readFile(KIND_RS, "utf8");
  const found = new Map();
  const re = /pub const (KIND_[A-Z0-9_]+): u32 = ([0-9_]+);/g;
  for (const match of source.matchAll(re)) {
    found.set(match[1], Number.parseInt(match[2].replaceAll("_", ""), 10));
  }

  const missing = WANTED.filter((name) => !found.has(name));
  if (missing.length > 0) {
    throw new Error(
      `kind.rs no longer defines: ${missing.join(", ")}. ` +
        "Either the constant was renamed upstream or WANTED is stale — " +
        "fix web/scripts/gen-kinds.mjs, do not hand-edit kinds.ts.",
    );
  }
  return WANTED.map((name) => [tsName(name), found.get(name)]);
}

function render(pairs) {
  const lines = pairs.map(([name, value]) => `  ${name}: ${value},`);
  return `// @generated by web/scripts/gen-kinds.mjs — DO NOT EDIT.
// Source of truth: crates/buzz-core/src/kind.rs
// Regenerate with: pnpm -C web gen:kinds

/** Nostr event kinds used by the web client, generated from buzz-core. */
export const KINDS = {
${lines.join("\n")}
} as const;

export type KindName = keyof typeof KINDS;
`;
}

const pairs = await parseKinds();
const rendered = render(pairs);

if (process.argv.includes("--check")) {
  let current = null;
  try {
    current = await readFile(OUT, "utf8");
  } catch {
    // missing file → stale
  }
  if (current !== rendered) {
    console.error(
      "web/src/shared/constants/kinds.ts is stale or hand-edited.\n" +
        "Run `pnpm -C web gen:kinds` and commit the result.",
    );
    process.exit(1);
  }
  console.log("kinds.ts is up to date with crates/buzz-core/src/kind.rs");
} else {
  await writeFile(OUT, rendered, "utf8");
  console.log(
    `wrote ${path.relative(projectRoot, OUT)} (${pairs.length} kinds)`,
  );
}
