// @generated by web/scripts/gen-kinds.mjs — DO NOT EDIT.
// Source of truth: crates/buzz-core/src/kind.rs
// Regenerate with: pnpm -C web gen:kinds

/** Nostr event kinds used by the web client, generated from buzz-core. */
export const KINDS = {
  PROFILE: 0,
  PERSONA: 30175,
  TEAM: 30176,
  MANAGED_AGENT: 30177,
  AGENT_RUNTIME_STATUS: 30900,
  INTEL_GATEWAY_CATALOG: 30901,
  AGENT_TURN_METRIC: 44200,
  AGENT_OBSERVER_FRAME: 24200,
  GIT_REPO_ANNOUNCEMENT: 30617,
  GIT_REPO_STATE: 30618,
} as const;

export type KindName = keyof typeof KINDS;
