// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as reposRouteImport } from "./routes/repos";
import { Route as intelligenceRouteImport } from "./routes/intelligence";
import { Route as indexRouteImport } from "./routes/index";
import { Route as reposDotrepoIdRouteImport } from "./routes/repos.$repoId";
import { Route as inviteDotcodeRouteImport } from "./routes/invite.$code";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as intelligenceDotagentsDotagentPubkeyRouteImport } from "./routes/intelligence.agents.$agentPubkey";
import { Route as reposDotrepoIdDotblobDotsplatRouteImport } from "./routes/repos.$repoId.blob.$";

const reposRoute = reposRouteImport.update({
  id: "/repos",
  path: "/repos",
  getParentRoute: () => rootRouteImport,
} as any);
const intelligenceRoute = intelligenceRouteImport.update({
  id: "/intelligence",
  path: "/intelligence",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const reposDotrepoIdRoute = reposDotrepoIdRouteImport.update({
  id: "/repos/$repoId",
  path: "/repos/$repoId",
  getParentRoute: () => rootRouteImport,
} as any);
const inviteDotcodeRoute = inviteDotcodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const intelligenceDotagentsDotagentPubkeyRoute =
  intelligenceDotagentsDotagentPubkeyRouteImport.update({
    id: "/intelligence/agents/$agentPubkey",
    path: "/intelligence/agents/$agentPubkey",
    getParentRoute: () => rootRouteImport,
  } as any);
const reposDotrepoIdDotblobDotsplatRoute =
  reposDotrepoIdDotblobDotsplatRouteImport.update({
    id: "/repos/$repoId/blob/$",
    path: "/repos/$repoId/blob/$",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/intelligence": typeof intelligenceRoute;
  "/repos": typeof reposRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/intelligence/agents/$agentPubkey": typeof intelligenceDotagentsDotagentPubkeyRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/intelligence": typeof intelligenceRoute;
  "/repos": typeof reposRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/intelligence/agents/$agentPubkey": typeof intelligenceDotagentsDotagentPubkeyRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/intelligence": typeof intelligenceRoute;
  "/repos": typeof reposRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/invite/$code": typeof inviteDotcodeRoute;
  "/repos/$repoId": typeof reposDotrepoIdRoute;
  "/intelligence/agents/$agentPubkey": typeof intelligenceDotagentsDotagentPubkeyRoute;
  "/repos/$repoId/blob/$": typeof reposDotrepoIdDotblobDotsplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/intelligence"
    | "/repos"
    | "/channels/$channelId"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/intelligence/agents/$agentPubkey"
    | "/repos/$repoId/blob/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/intelligence"
    | "/repos"
    | "/channels/$channelId"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/intelligence/agents/$agentPubkey"
    | "/repos/$repoId/blob/$";
  id:
    | "__root__"
    | "/"
    | "/intelligence"
    | "/repos"
    | "/channels/$channelId"
    | "/invite/$code"
    | "/repos/$repoId"
    | "/intelligence/agents/$agentPubkey"
    | "/repos/$repoId/blob/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  intelligenceRoute: typeof intelligenceRoute;
  reposRoute: typeof reposRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  inviteDotcodeRoute: typeof inviteDotcodeRoute;
  reposDotrepoIdRoute: typeof reposDotrepoIdRoute;
  intelligenceDotagentsDotagentPubkeyRoute: typeof intelligenceDotagentsDotagentPubkeyRoute;
  reposDotrepoIdDotblobDotsplatRoute: typeof reposDotrepoIdDotblobDotsplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/repos": {
      id: "/repos";
      path: "/repos";
      fullPath: "/repos";
      preLoaderRoute: typeof reposRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/intelligence": {
      id: "/intelligence";
      path: "/intelligence";
      fullPath: "/intelligence";
      preLoaderRoute: typeof intelligenceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId": {
      id: "/repos/$repoId";
      path: "/repos/$repoId";
      fullPath: "/repos/$repoId";
      preLoaderRoute: typeof reposDotrepoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$code": {
      id: "/invite/$code";
      path: "/invite/$code";
      fullPath: "/invite/$code";
      preLoaderRoute: typeof inviteDotcodeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/intelligence/agents/$agentPubkey": {
      id: "/intelligence/agents/$agentPubkey";
      path: "/intelligence/agents/$agentPubkey";
      fullPath: "/intelligence/agents/$agentPubkey";
      preLoaderRoute: typeof intelligenceDotagentsDotagentPubkeyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/repos/$repoId/blob/$": {
      id: "/repos/$repoId/blob/$";
      path: "/repos/$repoId/blob/$";
      fullPath: "/repos/$repoId/blob/$";
      preLoaderRoute: typeof reposDotrepoIdDotblobDotsplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  intelligenceRoute: intelligenceRoute,
  reposRoute: reposRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  inviteDotcodeRoute: inviteDotcodeRoute,
  reposDotrepoIdRoute: reposDotrepoIdRoute,
  intelligenceDotagentsDotagentPubkeyRoute:
    intelligenceDotagentsDotagentPubkeyRoute,
  reposDotrepoIdDotblobDotsplatRoute: reposDotrepoIdDotblobDotsplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
